-- Create a limited-privilege DB user for Liga EDUmind.
-- Replace ROLE_NAME, PASSWORD, and DATABASE_NAME before running.

DO
$$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ROLE_NAME') THEN
        CREATE ROLE ROLE_NAME LOGIN PASSWORD 'PASSWORD';
    END IF;
END
$$;

GRANT CONNECT ON DATABASE DATABASE_NAME TO ROLE_NAME;
GRANT USAGE ON SCHEMA public TO ROLE_NAME;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ROLE_NAME;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ROLE_NAME;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ROLE_NAME;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO ROLE_NAME;
