"""Add indexes

Revision ID: cb01274cf145
Revises: 002
Create Date: 2025-11-29 10:22:07.404138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb01274cf145'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipos', 'puntos_totales',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'ganados',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'empatados',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'perdidos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'puntos_juego_limpio',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'puntos_arbitro',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'puntos_grada',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_equipos_liga_id'), 'equipos', ['liga_id'], unique=False)
    op.add_column('ligas', sa.Column('public_pin', sa.String(length=6), nullable=True))
    op.alter_column('partidos', 'puntos_local',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_visitante',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_juego_limpio_local',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_juego_limpio_visitante',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_arbitro',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_grada_local',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_grada_visitante',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_partidos_equipo_local_id'), 'partidos', ['equipo_local_id'], unique=False)
    op.create_index(op.f('ix_partidos_equipo_visitante_id'), 'partidos', ['equipo_visitante_id'], unique=False)
    op.create_index(op.f('ix_partidos_jornada_id'), 'partidos', ['jornada_id'], unique=False)
    op.create_index(op.f('ix_partidos_liga_id'), 'partidos', ['liga_id'], unique=False)
    op.create_unique_constraint(None, 'tipos_deporte', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tipos_deporte', type_='unique')
    op.drop_index(op.f('ix_partidos_liga_id'), table_name='partidos')
    op.drop_index(op.f('ix_partidos_jornada_id'), table_name='partidos')
    op.drop_index(op.f('ix_partidos_equipo_visitante_id'), table_name='partidos')
    op.drop_index(op.f('ix_partidos_equipo_local_id'), table_name='partidos')
    op.alter_column('partidos', 'puntos_grada_visitante',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_grada_local',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_arbitro',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_juego_limpio_visitante',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_juego_limpio_local',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_visitante',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidos', 'puntos_local',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('ligas', 'public_pin')
    op.drop_index(op.f('ix_equipos_liga_id'), table_name='equipos')
    op.alter_column('equipos', 'puntos_grada',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'puntos_arbitro',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'puntos_juego_limpio',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'perdidos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'empatados',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'ganados',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equipos', 'puntos_totales',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
